### ISSUE TITLE
Error: java.lang.IllegalArgumentException: Invalid character found in method name [] . HTTP method names must be tokens

### ISSUE THREAD

**Issue by AAdewunmi** [spring-guides/tut-rest#109]
I had the same problem using Eclipse STS.

![Screenshot 2022-11-15 at 11 11 16](https://user-images.githubusercontent.com/15172744/201952129-cad76324-3e97-4435-b1a9-82100e63ea6d.png)

Mozilla Error:

![Screenshot 2022-11-15 at 11 11 01](https://user-images.githubusercontent.com/15172744/201952280-819bec51-e624-4c21-8149-0bffe7c34a74.png)

**Simple fix:**

It has to do with using http//: instead of https//: e.g.

Employee API makes the following call:

`$ curl -v localhost:8080/employees`

or

`$ curl -v https://localhost:8080/employees`

Orders API makes the following call:

`$ curl -v http://localhost:8080/orders`

Essentially, swapping "http" with "https", when testing your API end points, will fix the problem.

😎

**Comment by robertmcnees** [comment]
Hi @AAdewunmi. What error do you get when you run the curl commands from a terminal or command prompt? The error I see is from Mozilla and Eclipse STS which puts another layer in between the request and the response. When I went through the tutorial it worked with the commands as is, but did not work with `https`.

**Comment by robertmcnees** [comment]
Hi @AAdewunmi. Have you had the chance to look into this further? I'll leave this issue open for a bit longer but will close it soon if I don't hear back. Let me know if the issue persists.

**Comment by AAdewunmi** [comment]
Hi @robertmcnees, issue has been fixed, thanks.
