### ISSUE TITLE
Employee.java imports javax.persistence-api.* not found

### ISSUE THREAD

**Issue by bsheps** [spring-guides/tut-rest#117]
Following the spring rest tutorial from here: https://spring.io/guides/tutorials/rest/

Example code for nonrest/src/main/java/payroll/Employee.java does not work for java 17 (default version) initializer project.

May have found a workaround using `jakarta.persistence-api` instead. See here:

https://stackoverflow.com/questions/60021815/why-has-javax-persistence-api-been-replaced-by-jakarta-persistence-api-in-spring

**Comment by osBins** [comment]
Please update the tutorial page. I just spent 1 hour figuring out what was wrong with my IDE.

**Comment by robertmcnees** [comment]
Thanks for opening this issue! Getting the imports right is something we need to change. I'm going to close this issue as a duplicate since we have #116 open. 
PR #127 should close this issue.
