### ISSUE TITLE
Username and Password

### ISSUE THREAD

**Issue by prmallela** [spring-guides/tut-rest#16]
Can someone help me with the user name and password.

I have used the keytool for creating the keystore password.

**Comment by gregturn** [comment]
You have to spell out the issue you are having with keytool.

**Comment by SushmaBasavaraju** [comment]
I created the tomcat.keystore file under hateoas project resources folder. My application is running on localhost but i'm unable to login to Authentication Required login popup. i'm using UN:jhoeller and PW:password to login. Browser just refreshes and brings back the login popup again. 
URL: http://localhost:8080/jhoeller/bookmarks
![image](https://user-images.githubusercontent.com/29466120/27230789-134d84be-5276-11e7-8b8a-a909cd3a94de.png)

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
