### ISSUE TITLE
Security:curl work ,$.ajax got  401

### ISSUE THREAD

**Issue by phxism** [spring-guides/tut-rest#17]
when i use curl to get access_token
`curl -X POST -vu android-bookmarks:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d "password=password&username=jlong&grant_type=password&scope=write&client_secret=123456&client_id=android-bookmarks"`
it returns like
`{"access_token":"8ac3b71e-9196-4f01-b128-4fe2cf99a1c6","token_type":"bearer","refresh_token":"77a8657a-02fb-4e4a-a8bc-b2af5550540d","expires_in":43199,"scope":"write"}* Connection #0 to host localhost left intact`
then i use the token
`curl -v http://localhost:8080/bookmarks -H "Authorization: Bearer 8ac3b71e-9196-4f01-b128-4fe2cf99a1c6"`
it returns correct result `curl -v http://localhost:8080/bookmarks -H "Authorization: Bearer 8ac3b71e-9196-4f01-b128-4fe2cf99a1c6"`
but i use ajax in my host "localhost"
`$.ajax({
  url: 'http://localhost:8080/bookmarks',
  beforeSend: function (xhr) {
    xhr.setRequestHeader('Authorization', 'BEARER 8ac3b71e-9196-4f01-b128-4fe2cf99a1c6');
  },
  success: function (response) {
    console.log(response);
  }
});`
i use chrome console to run this ,it logs 
`XMLHttpRequest cannot load http://localhost:8080/bookmarks. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 401.`
i run the app append args :"--tagit.origin=*" to make Access-Control-Allow-Origin is always \* ,why it still get that error?

**Comment by yingdi11** [comment]
preflight request does not contains any header ... meaning there is not any authentication information. the request got rejected some how ... even did not come to the filter ... not sure how the project can be working . I am using angular $http call also facing the same issue ......

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
