### ISSUE TITLE
Required request body is missing: org.springframework.http.ResponseEntity<?> 

### ISSUE THREAD

**Issue by Gulivert** [spring-guides/tut-rest#23]
When you create the POST method add, and you try to call it from a request, it return the next:

{
"timestamp": 1480245744194,
"status": 400,
"error": "Bad Request",
"exception": "org.springframework.http.converter.HttpMessageNotReadableException",
"message": "Required request body is missing: org.springframework.http.ResponseEntity<?> com.garcia.bookmarks.BookmarkRestController.add(java.lang.String,com.garcia.bookmarks.Bookmark)",
"path": "/jhoeller/bookmarks"
}

All the other methods works fine, only this throw an error

**Comment by ruzalsh** [comment]
![screenshot 24](https://user-images.githubusercontent.com/26413934/29443270-aae40332-83f6-11e7-9afa-bfb3cb7c1cc9.png)


I also had same problem. I use "Postman" for json request. Codes are not wrong. I simply set content type to JSON(application/json) as shown in link for my code, and it worked.

**Comment by philipprus** [comment]
Hi. I don't see your code. 

Pls, check in your post method on server. Your need use @Requestbody Bookmark

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
