### ISSUE TITLE
Upgrade to the latest release of spring-boot-starter-parent

### ISSUE THREAD

**Issue by NicorDesigns** [spring-guides/tut-rest#26]
Upgrading to 1.4.3.RELEASE of spring-boot-starter-parent causes test failures in hateos module:

java.lang.AssertionError: Content type expected:<application/hal+json> but was:<application/hal+json;charset=UTF-8>

**Comment by gregturn** [comment]
Try it now since it's on 1.5.1.RELEASE.

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
