### ISSUE TITLE
readBookmark will find bookmarks of other users too

### ISSUE THREAD

**Issue by frank-orellana** [spring-guides/tut-rest#28]
If you put an id of a bookmark belonging to an user different than the one specified in the path, it will return it.

That happens because inside this method you are only searching by the id and not filtering by the user id:

```java
@RequestMapping(method = RequestMethod.GET, value = "/{bookmarkId}")
Bookmark readBookmark(@PathVariable String userId, @PathVariable Long bookmarkId) {
	this.validateUser(userId);
	return this.bookmarkRepository.findOne(bookmarkId);
}
```

It should be corrected to something like this:

```java
@RequestMapping(method = RequestMethod.GET, value = "/{bookmarkId}")
Bookmark readBookmark(@PathVariable String userId, @PathVariable Long bookmarkId) {
	this.validateUser(userId);
	return this.bookmarkRepository.findByAccountUsername(userId).stream()
	           .filter(bookmark -> bookmark.getId() == bookmarkId)
	           .findFirst()
	           .orElse(null);
}
```

**Comment by lgertel** [comment]
And with HATEOAS:

`
this.validateUser(userId);

        Customer c = this.customerRepository.findByAccountUsername(userId).stream()
                .filter(customer -> customer.getId() == customerId)
                .findFirst()
                .orElseThrow(
                        () -> new CustomerNotFoundException(customerId.toString())
                );

        return new CustomerResource(c);


`

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
