### ISSUE TITLE
Security sample project: Fix curl examples in Application

### ISSUE THREAD

**Issue by homer-jay** [spring-guides/tut-rest#29]
In class security/src/main/java/bookmarks/Application.java

At the top of it, we can see the following curl examples:
`// curl -X POST -vu android-bookmarks:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d "password=password&username=jlong&grant_type=password&scope=write&client_secret=123456&client_id=android-bookmarks"
// curl -v POST http://127.0.0.1:8080/bookmarks -H "Authorization: Bearer <oauth_token>""`

Both are wrong.

To begin with, for a self-signed certificate like the one generated in the tutorial, you need to run curl with the `--insecure` optional parameter.
The second command is also wrong. Its trying to post but instead of -X is using -v, and there is no actual payload. Double quotes at the end are also wrong.

Working examples (Edit the token in the second and third example):

LOGIN
`curl --insecure -X POST -vu android-bookmarks:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d "password=password&username=jlong&grant_type=password&scope=write&client_secret=123456&client_id=android-bookmarks"`

POSTING A NEW BOOKMARK
`curl --insecure -X POST -vu android-bookmarks:123456 -H "Authorization: Bearer <token returned in login response>" -H "Accept: application/json" -H "Content-Type: application/json" -d '{"uri": "https://spring.io", "description": "New bookmark!"}' https://127.0.0.1:8443/jlong/bookmarks`

RETRIEVING ALL BOOKMARKS
`curl -v --insecure -H "Accept: application/json" -H "Authorization: Bearer <token returned in login response>" -X GET https://127.0.0.1:8443/jlong/bookmarks/`

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
