### ISSUE TITLE
UserNotFoundException code does not contain imports

### ISSUE THREAD

**Issue by Coroecram** [spring-guides/tut-rest#33]
The code should be:

package bookmarks;

**import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;**

@ResponseStatus(HttpStatus.NOT_FOUND)
class UserNotFoundException extends RuntimeException {

	public UserNotFoundException(String userId) {
		super("could not find user '" + userId + "'.");
	}
}

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
