### ISSUE TITLE
Spring Initializr group should be bookmarks

### ISSUE THREAD

**Issue by Coroecram** [spring-guides/tut-rest#34]
You should tell the students that they should make the group name "bookmarks" when they create the initial Spring Boot application.

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
