### ISSUE TITLE
Use curl... to see JSON Response

### ISSUE THREAD

**Issue by Coroecram** [spring-guides/tut-rest#36]
The tutorial states:
"Use curl (or your browser) to see the JSON response from http://localhost:8080/jhoeller/bookmarks."
but the application should not even be running yet.

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
