### ISSUE TITLE
BookmarkControllerAdvice no imports

### ISSUE THREAD

**Issue by Coroecram** [spring-guides/tut-rest#39]
The tutorial does not contain the imports for this class.

Is there some norm I don't know where I have to copy and paste from the source code instead of the tutorial copy?

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
