### ISSUE TITLE
How to test "BookmarkRestController.readBookmarks(...)"?

### ISSUE THREAD

**Issue by ravikalla** [spring-guides/tut-rest#41]
I don't see any testing code for "BookmarkRestController.readBookmarks(...)". How can I test it?

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
