### ISSUE TITLE
Mime type */* is rendered wrong in README.adoc

### ISSUE THREAD

**Issue by rillig** [spring-guides/tut-rest#42]
It should be displayed as `*/*`, but is displayed as bold *`/`* instead. It's after `application/xml`.

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
