### ISSUE TITLE
Rest POM missing packaging type

### ISSUE THREAD

**Issue by pablorengi** [spring-guides/tut-rest#46]
tut-bookmarks/rest/pom.xml is missing the packaging type and will fail compile.

needs to add:

`<packaging>pom</packaging>`

**Comment by gregturn** [comment]
The whole thing builds fine, so not sure what the problem is.

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
