### ISSUE TITLE
Employee class needs default constructor

### ISSUE THREAD

**Issue by ocarlsen** [spring-guides/tut-rest#67]
Employee class needs default constructor for JPA.  Otherwise you will get an `org.hibernate.InstantiationException: No default constructor for entity` exception at the step to `curl -v localhost:8080/employees`.

**Comment by Lance-Drane** [comment]
I had to add private default constructors to Employee.java (and Order.java), and that seemed to fix the error for me (despite the compiler complaining that the constructors were unused):
```
@SuppressWarnings("unused")
private Employee() {
}
```

I suspect there's a better way to do this with Lombok, though.

**Comment by gregturn** [comment]
Resolved via #77.
