### ISSUE TITLE
Authority should be ROLE_USER not USER

### ISSUE THREAD

**Issue by alexcheng1982** [spring-guides/tut-rest#7]
In file https://github.com/spring-guides/tut-bookmarks/blob/master/security/src/main/java/bookmarks/Application.java#L143, `AuthorityUtils.createAuthorityList("USER", "write")` should be `AuthorityUtils.createAuthorityList("ROLE_USER", "write")` as Spring Security uses role `ROLE_USER` to check. This causes basic authentication to fail with `403` error.

Actually in the OAuth2 configuration (https://github.com/spring-guides/tut-bookmarks/blob/master/security/src/main/java/bookmarks/Application.java#L180), it's using the correct `ROLE_USER`.

**Comment by gregturn** [comment]
This tutorial was completely rewritten as of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983.

I suggest you read it from the top and be sure to let us know if you spot any issues!
