### ISSUE TITLE
spring-boot-maven-plugin:2.0.5.RELEASE  InvocationTargetException

### ISSUE THREAD

**Issue by thrasymache** [spring-guides/tut-rest#78]
The full error that I am getting when I run mvn clean spring-boot:run is:
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.0.5.RELEASE:run (default-cli) on project nonrest: An exception occurred while running. null: InvocationTargetException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException: javax.xml.bind.JAXBException -> [Help 1]

**Comment by gregturn** [comment]
Resolved via 3fc939c.
