### ISSUE TITLE
Unable to marshal type "bookmarks.BookmarkResource"

### ISSUE THREAD

**Issue by darrylb-github** [spring-guides/tut-rest#8]
When running the HATEOAS project as is and browsing to http://localhost:8080/jhoeller/bookmarks I get the following error:

```
There was an unexpected error (type=Internal Server Error, status=500).
Could not marshal [Resources { content: [links: [<http://bookmark.com/1/jhoeller>;rel="bookmark-uri", <http://localhost:8080/jhoeller/bookmarks>;rel="bookmarks", <http://localhost:8080/jhoeller/bookmarks/1>;rel="self"], links: [<http://bookmark.com/2/jhoeller>;rel="bookmark-uri", <http://localhost:8080/jhoeller/bookmarks>;rel="bookmarks", <http://localhost:8080/jhoeller/bookmarks/2>;rel="self"]], links: [] }]: null; 
nested exception is javax.xml.bind.MarshalException - with linked exception: [com.sun.istack.internal.SAXException2: 
unable to marshal type "bookmarks.BookmarkResource" as an element because it is missing an @XmlRootElement annotation]
```

Is there something missing here or is it just me?

**Comment by ekapinos** [comment]
Helped for me too. TNX. A lot of typo I've found in this tutorial. So seems it is correct fix.

**Comment by ziftytodd** [comment]
For anyone else hitting this error, if you still want to return a true HATEOAS resource (versus a straight-up Collection), change the `@RequestMapping` on the `readBookmarks` method to include a `produces` attribute:

    @RequestMapping(method = RequestMethod.GET, produces = {MediaType.APPLICATION_JSON_VALUE, "application/hal+json"})

Don't forget to import `import org.springframework.http.MediaType;`

**Comment by jflewis** [comment]
Is this happening for everyone because I've run into the same issue. Should the above fix by @ziftytodd be implemented? Sorry to bring up a 2 year old issue

**Comment by LeonardGC** [comment]
@jflewis I did the tutorial just now and was glad to find this page to solve this issue. The fix of @ziftytodd should be implemented asap.
There are other issues with this tutorial as well, like the pointing to the wrong source code (at the start of the tutorial), the addition of the org.springframework.security.oauth dependency from the beginning, (so the examples don't work but are asking for a username and password), etc...
Very confusing.

**Comment by cal0610** [comment]
It would also be interesting to see how to test methods readSingleBookmark and readBookmarks after using hateoas links...
