### ISSUE TITLE
Cannot run code at specific point in guide

### ISSUE THREAD

**Issue by antloewe** [spring-guides/tut-rest#81]
Hello,

when you are in the chapter "Evolving REST APIs", after changing the Employee class and making the changes in the code snippet "POST that handles "old" and "new" client requests", you cannot run the code because you changed the constructor in the Employee class but in the LoadDatabase class you still use the (old) constructor which gets a name (String) and a role (String).

**Comment by UgmaDevelopment** [comment]
Sorry, I meant to type 91, not 81. Ignore my mentioning this issue.

**Comment by UgmaDevelopment** [comment]
I believe, in PR #94 I've somewhat resolved your concern by adding a tip about changing your existing code to use the new constructor.

**Comment by gregturn** [comment]
Let's see if #94 can be wrapped up and merged (please read my comments over there @UgmaDevelopment), and if that resolves this issues listed here.

**Comment by gregturn** [comment]
#94  has been merged and closed.

@antloewe, can you give the tutorial a spin and see if there are still any gaps?

**Comment by mlvandijk** [comment]
Imho this is covered by the note "Don’t forget to go and change how you preload your database (in LoadDatabase) to use this new constructor."

**Comment by robertmcnees** [comment]
The tutorial works as is, so this issue was likely fixed by previous commits as referenced in the [https://github.com/spring-guides/tut-rest/issues/81#issuecomment-634841782](comments history). Closing the issue.
