### ISSUE TITLE
Cannot find stream method

### ISSUE THREAD

**Issue by FabioFriz** [spring-guides/tut-rest#83]
Hi,
I had some problems with stream method, so I had to substitute each call like `repository.findAll().stream()` with `StreamSupport.stream(repository.findAll().spliterator(), false)`.

**Comment by gregturn** [comment]
The first thing that comes to mind is, are you using Java 8+, or Java 7. Because the `stream()` method being added to `java.util.Collection` (parent interface of `java.util.List`) isn't until JDK 8.

**Comment by FabioFriz** [comment]
It's the same thing I thought of, but I'm using Java 11.0.2

**Comment by zain1612** [comment]
https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html
returns a Iterable<T>on findAll. Greg perhaps update the tutorial?

**Comment by gregturn** [comment]
As of https://github.com/spring-guides/tut-rest/commit/63d393748ec27b072854f8b35a763e27ac6e0983, all the repositories extend `JpaRepository` from Spring Data JPA, not `CrudRepository` from Spring Data Commons. 

The `findAll()` method returns a `List`, so `.stream()` is available.
