### ISSUE TITLE
HATEOS related section of the tutorial is outdated

### ISSUE THREAD

**Issue by so-langsam** [spring-guides/tut-rest#84]
I had some touble working throught the part of the tutorial that had to do with the `spring-boot-starter-hateoas`. This dependency gets introduced in the "What makes something RESTful?" section.

It seems the code examples are based on an older version of this dependency.

Following the information [here](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#migrate-to-1.0) helped me get through the tutorial.

The tutorial itself was really nice.

**Comment by Yupla** [comment]
Thank you for the link !

**Comment by red-willow-work** [comment]
I ran into the same issue that Sam (so-langsam) reported.  I've updated my project with the current Spring HATEOAS 1.0.1 version, and I would like to contribute and update this tutorial to do the same.  How do I go about doing that?

**Comment by zain1612** [comment]
yep seems outdated as of dec 2019.
This helped https://stackoverflow.com/questions/25352764/hateoas-methods-not-found

**Comment by gregturn** [comment]
Check out the latest changes and tell if there is yet more to work on.

**Comment by mahonelee** [comment]
Yes, it takes me lots of time to fix. Here is the old version code in the doc:
```java
@GetMapping("/employees/{id}")
Resource<Employee> one(@PathVariable Long id) {

  Employee employee = repository.findById(id)
    .orElseThrow(() -> new EmployeeNotFoundException(id));

  return new Resource<>(employee,
    linkTo(methodOn(EmployeeController.class).one(id)).withSelfRel(),
    linkTo(methodOn(EmployeeController.class).all()).withRel("employees"));
}
```
The class `org.springframework.hateoas.Resource` was changed to `org.springframework.hateoas.EntityModel`.
The spring team just changed the class name. What a funny bug I have never met.😂

**Comment by gregturn** [comment]
I just checked, and that section now reads:

```java
@GetMapping("/employees/{id}")
EntityModel<Employee> one(@PathVariable Long id) {

  Employee employee = repository.findById(id)
    .orElseThrow(() -> new EmployeeNotFoundException(id));

  return new EntityModel<>(employee,
    linkTo(methodOn(EmployeeController.class).one(id)).withSelfRel(),
    linkTo(methodOn(EmployeeController.class).all()).withRel("employees"));
}
```

**Comment by gregturn** [comment]
The reference docs explain why this name change was made => https://docs.spring.io/spring-hateoas/docs/1.1.0.BUILD-SNAPSHOT/reference/html/#migrate-to-1.0.changes.representation-models

**Comment by gregturn** [comment]
Also, check out https://spring.io/blog/2019/03/05/spring-hateoas-1-0-m1-released.

**Comment by gregturn** [comment]
Seeing no other obvious changes, I'm going to close this issue.

If you spot issues, feel free to reopen this ticket.
