### ISSUE TITLE
Duplicated, outdated tutorial

### ISSUE THREAD

**Issue by UgmaDevelopment** [spring-guides/tut-rest#93]
Hello!

I was following the tutorial at https://spring.io/guides/tutorials/bookmarks/ about Rest Services, when I came to [a section] that wouldn't compile for me.

[a section]: https://spring.io/guides/tutorials/bookmarks/#_what_makes_something_restful

Upon a little googling [StackOverflow told me] that `Resource` had been renamed `EntityModel`, but **more importantly**, [in the comments], I spied another URL (https://spring.io/guides/tutorials/rest/) for this same "Building REST services with Spring" tutorial on spring's website.

[StackOverflow told me]: https://stackoverflow.com/a/59199967/5432315
[in the comments]: https://stackoverflow.com/questions/25352764/hateoas-methods-not-found#comment107150425_59199967

It appears that the tutorial I was originally reading is an old version of the tutorial that contains multiple mistakes and the aforementioned stumbling block.

I bring this up so that this duplicate tutorial (https://spring.io/guides/tutorials/bookmarks/) can be taken down and all links referring to it can be changed to refer to the updated tutorial <small><small><small>(https://spring.io/guides/tutorials/rest/)</small></small></small>.

What can I do to help in this endeavor?

**Comment by gregturn** [comment]
spring.io delegates to github. Hence, https://spring.io/guides/tutorials/bookmarks/ translates to github.com/spring-guides/tut-bookmark, and /guides/tutorials/rest -> /spring-guides/tut-rest.

Since tut-bookmark was simply moved to tut-rest, github put a redirect in place, which we have no control over.

**Comment by gregturn** [comment]
Since we can't really do anything about this, I'm closing this issue.

**Comment by UgmaDevelopment** [comment]
If GitHub was redirecting to the new tutorial, that would be fine; then it wouldn't have any of the mistakes I was talking about . 

However, it doesn't appear to be doing that; it appears to be pointing to an old version of the tutorial that has the mistakes and which goes un-updated. 

If https://github.com/spring-guides/tut-bookmark doesn't exist anymore how can it be showing that old content? If Github was redirecting, it would show the new content, right? To me it seems like there's a rendered file of the bookmark tutorial that needs to be gotten rid of or turned into a redirect.

**Comment by gregturn** [comment]
It's https://github.com/spring-guides/tut-bookmarks.

When you rename a repository, github puts in the redirect. And I found, spring.io works PERFECTLY with that. Or rather...IM-perfectly.

**Comment by gregturn** [comment]
Join me on https://gitter.im/spring-projects/spring-hateoas and we can discuss this more interactively.
